DELETE http://localhost:3003/api/blogs/6761d7344e86d60616b7fe24
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhanV1a2tvIiwiaWQiOiI2NzYxYzk4MTlhYmYxMDlkNWYyYWM4MzUiLCJpYXQiOjE3MzQ0NjUzNTd9.1GlpcgaVjAkxphaLKLzfsSBkI49peT9dkqnb2Z0MzAA