POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhanV1a2tvIiwiaWQiOiI2NzYxYzk4MTlhYmYxMDlkNWYyYWM4MzUiLCJpYXQiOjE3MzQ0NjUzNTd9.1GlpcgaVjAkxphaLKLzfsSBkI49peT9dkqnb2Z0MzAA

{
	"title": "testi",
	"author": "Raju Ukko",
	"url": "www.testi.fi",
	"userId": "6761c9819abf109d5f2ac835",
	"likes": 123
}